# Generated by Django 3.2.6 on 2023-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(max_length=500)),
                ('lastname', models.TextField(max_length=500, null=True)),
                ('sex', models.TextField(max_length=10)),
                ('dateofbirth', models.IntegerField()),
                ('current_address', models.TextField(max_length=500)),
            ],
        ),
    ]
