# Generated by Django 3.2.6 on 2023-03-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_reader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reader',
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
