# Generated by Django 4.1.7 on 2023-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='lastname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=1500),
        ),
    ]
