# Generated by Django 4.1.7 on 2023-03-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_author_firstname_alter_author_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
