# Generated by Django 4.1.7 on 2023-03-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_author_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
