# Generated by Django 4.1.7 on 2023-03-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
